/* The following code was generated by JFlex 1.3.5 on 27.3.2020, 11:38 */

package cup.grammar;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;



public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\15\6\0"+
    "\1\47\1\50\1\46\1\44\1\0\1\45\1\26\1\0\12\4\1\0"+
    "\1\43\1\42\1\14\1\13\2\0\1\22\1\5\1\24\1\16\1\25"+
    "\3\5\1\17\4\5\1\23\1\5\1\40\1\5\1\27\1\20\1\21"+
    "\1\5\1\33\4\5\4\0\1\5\1\0\1\6\1\35\1\5\1\10"+
    "\1\32\3\5\1\34\2\5\1\31\1\5\1\7\1\11\2\5\1\12"+
    "\1\36\1\37\1\30\3\5\1\41\1\5\uff85\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    41,    82,    41,   123,   164,   205,   164,   246,   287, 
      328,   369,   410,   451,    41,   492,   533,   574,    41,    41, 
       41,    41,    41,    41,    41,   615,   164,    41,    41,    41, 
      656,   697,   738,   779,   820,   164,   861,   902,   943,   984, 
     1025,  1066,  1107,   164,  1148,  1189,  1230,  1271,  1312,  1353, 
     1394,  1435,  1476,  1517,  1558,  1599,  1640,  1681,   164,  1722, 
     1763,   164,  1804,   164,   164
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\6"+
    "\1\11\1\6\1\12\1\13\1\14\1\15\5\6\1\16"+
    "\1\6\1\17\1\20\3\6\1\21\4\6\1\22\1\6"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\53\0"+
    "\1\4\52\0\1\5\50\0\7\6\3\0\10\6\1\0"+
    "\13\6\13\0\3\6\1\32\3\6\3\0\10\6\1\0"+
    "\13\6\13\0\6\6\1\33\3\0\10\6\1\0\13\6"+
    "\23\0\1\34\47\0\1\35\51\0\1\36\40\0\7\6"+
    "\3\0\1\6\1\37\6\6\1\0\13\6\13\0\5\6"+
    "\1\40\1\6\3\0\10\6\1\0\13\6\13\0\7\6"+
    "\3\0\10\6\1\0\1\6\1\41\11\6\13\0\2\6"+
    "\1\42\4\6\3\0\10\6\1\0\13\6\13\0\6\6"+
    "\1\43\3\0\10\6\1\0\13\6\13\0\4\6\1\44"+
    "\2\6\3\0\10\6\1\0\13\6\13\0\7\6\3\0"+
    "\2\6\1\45\5\6\1\0\13\6\13\0\3\6\1\46"+
    "\3\6\3\0\10\6\1\0\13\6\13\0\7\6\3\0"+
    "\10\6\1\0\2\6\1\47\10\6\13\0\6\6\1\50"+
    "\3\0\10\6\1\0\13\6\13\0\7\6\3\0\10\6"+
    "\1\0\5\6\1\51\5\6\13\0\7\6\3\0\3\6"+
    "\1\52\4\6\1\0\13\6\13\0\7\6\3\0\10\6"+
    "\1\0\7\6\1\53\3\6\13\0\7\6\3\0\10\6"+
    "\1\0\3\6\1\54\7\6\13\0\7\6\3\0\10\6"+
    "\1\0\5\6\1\55\5\6\13\0\5\6\1\56\1\6"+
    "\3\0\10\6\1\0\13\6\13\0\7\6\3\0\4\6"+
    "\1\57\3\6\1\0\13\6\13\0\7\6\3\0\10\6"+
    "\1\0\10\6\1\60\2\6\13\0\2\6\1\61\4\6"+
    "\3\0\10\6\1\0\13\6\13\0\6\6\1\62\3\0"+
    "\10\6\1\0\13\6\13\0\7\6\3\0\5\6\1\63"+
    "\2\6\1\0\13\6\13\0\6\6\1\64\3\0\10\6"+
    "\1\0\13\6\13\0\7\6\3\0\10\6\1\0\6\6"+
    "\1\65\4\6\13\0\7\6\3\0\10\6\1\0\5\6"+
    "\1\66\5\6\13\0\7\6\3\0\6\6\1\67\1\6"+
    "\1\0\13\6\13\0\2\6\1\70\4\6\3\0\10\6"+
    "\1\0\13\6\13\0\7\6\3\0\10\6\1\0\2\6"+
    "\1\71\10\6\13\0\7\6\3\0\10\6\1\0\10\6"+
    "\1\72\2\6\13\0\7\6\3\0\7\6\1\73\1\0"+
    "\13\6\13\0\7\6\3\0\10\6\1\0\5\6\1\74"+
    "\5\6\13\0\7\6\3\0\10\6\1\0\3\6\1\75"+
    "\7\6\13\0\7\6\3\0\10\6\1\0\12\6\1\76"+
    "\13\0\3\6\1\77\3\6\3\0\10\6\1\0\13\6"+
    "\13\0\7\6\3\0\10\6\1\0\7\6\1\100\3\6"+
    "\13\0\7\6\3\0\10\6\1\0\10\6\1\101\2\6"+
    "\7\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  9,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  1, 
     1,  1,  9,  9,  9,  9,  9,  9,  9,  1,  1,  9,  9,  9,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	

    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[1845];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 134) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 28: 
          {  return symbolFactory.newSymbol("IMPLICATION", IMPLICATION);  }
        case 66: break;
        case 43: 
          {  return symbolFactory.newSymbol("RULE", RULE);  }
        case 67: break;
        case 18: 
          {  return symbolFactory.newSymbol("LESS", LESS);  }
        case 68: break;
        case 19: 
          {  return symbolFactory.newSymbol("SEMI", SEMI);  }
        case 69: break;
        case 20: 
          {  return symbolFactory.newSymbol("PLUS", PLUS);  }
        case 70: break;
        case 63: 
          {  return symbolFactory.newSymbol("VARIABLES", VARIABLES);  }
        case 71: break;
        case 26: 
          {  return symbolFactory.newSymbol("OR", OR);  }
        case 72: break;
        case 7: 
          {  return symbolFactory.newSymbol("UMINUS", UMINUS);  }
        case 73: break;
        case 23: 
          {  return symbolFactory.newSymbol("LPAREN", LPAREN);  }
        case 74: break;
        case 24: 
          {  return symbolFactory.newSymbol("RPAREN", RPAREN);  }
        case 75: break;
        case 4: 
          {  return symbolFactory.newSymbol("NUMBER", NUMBER, Integer.parseInt(yytext()));  }
        case 76: break;
        case 2: 
        case 3: 
          {   }
        case 77: break;
        case 27: 
          {  return symbolFactory.newSymbol("GREATER", GREATER);  }
        case 78: break;
        case 14: 
          {  return symbolFactory.newSymbol("POINT", POINT);  }
        case 79: break;
        case 10: 
          {  return symbolFactory.newSymbol("EQUAL", EQUAL);  }
        case 80: break;
        case 21: 
          {  return symbolFactory.newSymbol("MINUS", MINUS);  }
        case 81: break;
        case 22: 
          {  return symbolFactory.newSymbol("TIMES", TIMES);  }
        case 82: break;
        case 5: 
        case 6: 
        case 8: 
        case 12: 
        case 13: 
        case 15: 
        case 16: 
        case 17: 
        case 25: 
        case 30: 
        case 31: 
        case 32: 
        case 33: 
        case 34: 
        case 36: 
        case 37: 
        case 38: 
        case 39: 
        case 40: 
        case 41: 
        case 42: 
        case 44: 
        case 45: 
        case 46: 
        case 47: 
        case 48: 
        case 49: 
        case 50: 
        case 51: 
        case 52: 
        case 53: 
        case 54: 
        case 55: 
        case 56: 
        case 57: 
        case 59: 
        case 60: 
        case 62: 
          {  return symbolFactory.newSymbol("NAME", NAME, String.valueOf(yytext()));  }
        case 83: break;
        case 1: 
        case 9: 
        case 11: 
          {  emit_warning("Unrecognized character '" +yytext()+"' -- ignored");  }
        case 84: break;
        case 64: 
          {  return symbolFactory.newSymbol("CONSTRAINT", CONSTRAINT);  }
        case 85: break;
        case 35: 
          {  return symbolFactory.newSymbol("AND", AND);  }
        case 86: break;
        case 61: 
          {  return symbolFactory.newSymbol("PRIORITY", PRIORITY);  }
        case 87: break;
        case 58: 
          {  return symbolFactory.newSymbol("DISTANCE", DISTANCE);  }
        case 88: break;
        case 29: 
          {  return symbolFactory.newSymbol("NONEQUAL", NONEQUAL);  }
        case 89: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {      return symbolFactory.newSymbol("EOF", EOF, new Location(yyline+1,yycolumn+1,yychar), new Location(yyline+1,yycolumn+1,yychar+1));
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
