
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.grammar;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 21;
  public static final int AND = 4;
  public static final int PLUS = 18;
  public static final int RPAREN = 17;
  public static final int OR = 5;
  public static final int EQUAL = 8;
  public static final int SEMI = 15;
  public static final int POINT = 6;
  public static final int NAME = 23;
  public static final int GREATER = 3;
  public static final int IMPLICATION = 2;
  public static final int LPAREN = 16;
  public static final int NONEQUAL = 9;
  public static final int PRIORITY = 12;
  public static final int VARIABLES = 11;
  public static final int NUMBER = 22;
  public static final int EOF = 0;
  public static final int CONSTRAINT = 13;
  public static final int RULE = 10;
  public static final int MINUS = 19;
  public static final int error = 1;
  public static final int DISTANCE = 7;
  public static final int LESS = 14;
  public static final int UMINUS = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IMPLICATION",
  "GREATER",
  "AND",
  "OR",
  "POINT",
  "DISTANCE",
  "EQUAL",
  "NONEQUAL",
  "RULE",
  "VARIABLES",
  "PRIORITY",
  "CONSTRAINT",
  "LESS",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "NUMBER",
  "NAME"
  };
}

